name: Environment Variables Demo

on:
  workflow_dispatch:

jobs:
  env-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Build"

      - name: Cleanup
        if: always()
        run: echo "Cleanup always runs."
